// import express
const express = require('express')
const router=new express.Router()
const register = require('../controller/registercontroller')
const loginuser = require('../controller/logincontrollers')
const adminregister = require('../controller/adminregister')
const adminlogin=require('../controller/adminlogin')
const teacherregister=require('../controller/teacherregister')
const teacherlogin=require('../controller/teacherlogin')
const viewstudent=require('../viewcontroller/studentsview')
const teacherview=require('../viewcontroller/teacherview')
const message= require('../dbdata/admindata')
const deletemessage=require('../dbdata/admindata')
const viewmessage=require('../viewcontroller/viewmsg')
const token=require('../controller/token')
const deletestudent=require('../viewcontroller/deletestudent')
const viewresults=require('../viewcontroller/viewscore')
const images=require('../viewcontroller/viewimage')
const viewregisterstudent=require('../viewcontroller/registredstudents')

router.post('/register',register.addstudent)
router.post('/login',loginuser.finduser)
router.post('/adminregister',adminregister.addadmin)
router.post('/adminlogin',adminlogin.findadmin)
router.post('/teacherregister',teacherregister.addteacher)
router.post('/teacherlogin',teacherlogin.finduser)
router.get('/viewstudents',token.jwtmiddleware,viewstudent.viewstudent)
router.get('/viewteachers',token.jwtmiddleware,teacherview.viewstaff)
router.post('/notification',message.adddata)
router.delete('/delete/:id',deletemessage.deleteddata)
router.get('/getnotification',viewmessage.viewmessage)
router.delete('/deleteteacher/:id',token.jwtmiddleware,teacherregister.removeteacher)
router.delete('/deletestudent/:id',token.jwtmiddleware,deletestudent.deletestudent),
router.put('/updateresult',token.jwtmiddleware,register.results)
router.get('/viewresult/:id',token.jwtmiddleware,viewresults.viewscore)
router.get('/getimages',images.imagedata)
router.get('/registeredstudentsview',viewregisterstudent.viewregisterstudents)
module.exports=router